// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!
namespace Glider.Core.SerializableData
{
    /// <summary>
    /// 유저가 획득 가능한 모든 에셋을 미리 정의
    /// </summary>
	public enum AcquirableAssetType
	{
		Currency = 0,
		Equipment = 1,
		Skill = 2,
		None = 3,
		Undefined = -1
	}
}
