// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!
namespace Glider.Core.SerializableData
{
    /// <summary>
    /// 금화, 보석 등 화폐성 재화 데이터
    /// </summary>
	public enum CurrencyKey
	{
		Coin = 0,
		Dia = 1,
		None = 2,
		Gold = 3,
		Undefined = -1
	}
}
