// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!
namespace Glider.Core.SerializableData
{
	public enum GoodType
	{
		Coin = 0,
		Dia = 1,
		Undefined = -1
	}
}
