// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

namespace Glider.Core.SerializableData
{
    public enum PurchaseLimPurchaseLimitType
    {
        None = 0,
        Daily = 1,
        Weekly = 2,
        Monthly = 3,
        Character = 4,
        User = 5,
    }
}