// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!
namespace Glider.Core.SerializableData
{
	public enum QuestType
	{
		KillEnemy = 0,
		ClearWave = 1,
		ReachAttackLevel = 2,
		ReachAttackPointLevel = 3,
		PurchaseDia = 4,
		Undefined = -1
	}
}
