// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!
namespace Glider.Core.SerializableData
{
	public enum ResearchType
	{
		Attack = 0,
		AttackPoint = 1,
		Undefined = -1
	}
}
