:: **********************************
:: 자동생성 깃 디렉토리 - 절대경로 지정
set git_path="C:\Users\PSG\Desktop\auto-create-csfile"
set dotnet_version="net6.0"
:: **********************************


set copy_from_git_path="./copy-from-git"
set create_local_file_path="./create-local-file"


:: copy-from-git
dotnet build %copy_from_git_path%
%copy_from_git_path%"/bin/Debug/"%dotnet_version%"/copy-from-git.exe" %git_path% %create_local_file_path%


:: create-local-file
dotnet build %create_local_file_path% /nowarn:CA2200,CS8600,CS8604,CS0219,CS8618,CS0649
%create_local_file_path%"/bin/Debug/"%dotnet_version%"/create-local-file.exe"


:: sln
:: 유니티 프로젝트로 대체
::dotnet new sln --name AutoGenerated --force
::dotnet new console --name AutoGenerated --force
::dotnet add "./AutoGenerated/AutoGenerated.csproj" reference "./AutoGenerated/Assets/NewtonSoft/Newtonsoft.Json.dll"
::dotnet sln add "./AutoGenerated/AutoGenerated.sln"
xcopy %create_local_file_path%"/Newtonsoft" "./AutoGenerated/Assets/NewtonSoft" /s /e /y /i

pause