:: **********************************
:: modify path
set git_path="C:\Users\GAME DUO\Desktop\auto-create-csfile"
:: **********************************

set dotnet_version="net6.0"
::set current_path="C:\Users\GAME DUO\Desktop\local-auto-create-csfile"
::cd %current_path%

set copy_from_git_path="./copy-from-git"
set create_local_file_path="./create-local-file"


:: copy-from-git
dotnet build %copy_from_git_path%
%copy_from_git_path%"/bin/Debug/"%dotnet_version%"/copy-from-git.exe" %git_path% %create_local_file_path%

:: 타겟 자동생성 폴더 삭제
rmdir "./AutoGenerated/Assets/LocalCreated/CloudData" /s /q
rmdir "./AutoGenerated/Assets/LocalCreated/Enums" /s /q
rmdir "./AutoGenerated/Assets/LocalCreated/StaticData" /s /q

:: create-local-file
dotnet build %create_local_file_path% /nowarn:CA2200,CS8600,CS8604,CS0219,CS8618,CS0649
%create_local_file_path%"/bin/Debug/"%dotnet_version%"/create-local-file.exe"


:: sln
:: --------------------------------------------
::dotnet new sln --name AutoGenerated --force
::dotnet new console --name AutoGenerated --force
::dotnet add "./AutoGenerated/AutoGenerated.csproj" reference "./AutoGenerated/Assets/NewtonSoft/Newtonsoft.Json.dll"
::dotnet sln add "./AutoGenerated/AutoGenerated.sln"
xcopy %create_local_file_path%"/Newtonsoft" "./AutoGenerated/Assets/NewtonSoft" /s /e /y /i

pause