// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
    /// <summary>
    /// 유저가 획득할 수 있는 모든 에셋
    /// </summary>
    [Serializable]
    public class AcquirableAsset
    {
        [SerializeField] private AcquirableAssetType acquirableAssetKey;
        public AcquirableAssetType AcquirableAssetKey => acquirableAssetKey;

        [SerializeField] private int keyIndex;
        public int KeyIndex => keyIndex;

        [SerializeField] private double value;
        public double Value => value;

        [SerializeField] private int[] param;
        public int[] Param => param;
    }
}