// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public class rateClass
	{
        [SerializeField] private double[] rate;
        public double[] Rate => rate;

        [SerializeField] private string rateName;
        public string RateName => rateName;

        [SerializeField] private long test;
        public long Test => test;

        [SerializeField] private byte testsetset;
        public byte Testsetset => testsetset;

	}
}
