// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public class StaticDataQuestType
	{
        [SerializeField] private LocalizedMessageKey descLmk;
        public LocalizedMessageKey DescLmk => descLmk;

        [SerializeField] private QuestType questType;
        public QuestType QuestType => questType;

	}
}
