// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public class StaticDataDeck
	{
        [SerializeField] private int availableDeckSlots;
        public int AvailableDeckSlots => availableDeckSlots;

        [SerializeField] private int availableEquipmentSlots;
        public int AvailableEquipmentSlots => availableEquipmentSlots;

        [SerializeField] private int availableSkillSlots;
        public int AvailableSkillSlots => availableSkillSlots;

	}
}
