// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public class StaticDataQuest
	{
        [SerializeField] private int goal;
        public int Goal => goal;

        [SerializeField] private int id;
        public int Id => id;

        [SerializeField] private int indicatingLevel;
        public int IndicatingLevel => indicatingLevel;

        [SerializeField] private int nextQuest;
        public int NextQuest => nextQuest;

        [SerializeField] private QuestType questType;
        public QuestType QuestType => questType;

        [SerializeField] private GoodType rewardGoodKey;
        public GoodType RewardGoodKey => rewardGoodKey;

        [SerializeField] private double rewardGoodValue;
        public double RewardGoodValue => rewardGoodValue;

        [SerializeField] private int specialEvent;
        public int SpecialEvent => specialEvent;

        [SerializeField] private int subType;
        public int SubType => subType;

        [SerializeField] private string targetButton;
        public string TargetButton => targetButton;

        [SerializeField] private string targetPanel;
        public string TargetPanel => targetPanel;

	}
}
