// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
    /// <summary>
    /// 금화, 보석 등 화폐성 재화 데이터
    /// </summary>
	[Serializable]
	public class StaticDataCurrency
	{
        [SerializeField] private CurrencyKey key;
        public CurrencyKey Key => key;

        [SerializeField] private LocalizedMessageKey lmkName;
        public LocalizedMessageKey LmkName => lmkName;

	}
}
