// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
    /// <summary>
    /// 인앱상품 : 구성품 (1:N)
    /// </summary>
	[Serializable]
	public class StaticDataInAppProductContent
	{
        [SerializeField] private int id;
        public int Id => id;

        [SerializeField] private int inAppProductId;
        public int InAppProductId => inAppProductId;

        [SerializeField] private int priceInKrw;
        public int PriceInKrw => priceInKrw;

	}
}
