// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
    [Serializable]
    public class StaticDataUnitInfo
    {
        [SerializeField] private float[] attackDamage;
        public float[] AttackDamage => attackDamage;

        [SerializeField] private float[] hp;
        public float[] Hp => hp;

        [SerializeField] private int unitId;
        public int UnitId => unitId;
    }
}