// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
    /// <summary>
    /// 인앱 상품 정의
    /// </summary>
	[Serializable]
	public class StaticDataInAppProduct
	{
        [SerializeField] private int[] acquirableAssetIds;
        public int[] AcquirableAssetIds => acquirableAssetIds;

        [SerializeField] private string displayEndTime;
        public string DisplayEndTime => displayEndTime;

        [SerializeField] private string displayStartTime;
        public string DisplayStartTime => displayStartTime;

        [SerializeField] private int id;
        public int Id => id;

        [SerializeField] private bool isDisplayTimeLimited;
        public bool IsDisplayTimeLimited => isDisplayTimeLimited;

        [SerializeField] private LocalizedMessageKey lmkDesc;
        public LocalizedMessageKey LmkDesc => lmkDesc;

        [SerializeField] private LocalizedMessageKey lmkTitle;
        public LocalizedMessageKey LmkTitle => lmkTitle;

        [SerializeField] private string productId;
        public string ProductId => productId;

        [SerializeField] private int purchaseLimit;
        public int PurchaseLimit => purchaseLimit;

        [SerializeField] private PurchaseLimitType purchaseLimitType;
        public PurchaseLimitType PurchaseLimitType => purchaseLimitType;

	}
}
