// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public struct CharacterCurrency
	{
		/// <summary>
		/// 누적 획득 값
		/// </summary>
		public double totalValue;

		/// <summary>
		/// 현재 보유한 값
		/// </summary>
		public double value;

		public int CreateCrdCode()
		{
			var crc = 2147483647;
			crc ^= totalValue.GetHashCode();
			crc ^= value.GetHashCode();
			return crc;
		}
	}
}
