// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public struct CharacterSkill
	{
		public double totalValue;

		public double value;

		public int CreateCrdCode()
		{
			var crc = 2147483647;
			crc ^= totalValue.GetHashCode();
			crc ^= value.GetHashCode();
			return crc;
		}
	}
}
