// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public struct CharacterEquipment
	{
		public EquipmentKey equipmentKey;

		public int level;

		public string uuid;

		public int CreateCrdCode()
		{
			var crc = 2147483647;
			crc ^= equipmentKey.GetHashCode();
			crc ^= level.GetHashCode();
			if(uuid!=null) crc ^= uuid.GetHashCode();
			return crc;
		}
	}
}
