// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
    /// <summary>
    /// 유저가 보유 중인 Currency 재화
    /// </summary>
    [Serializable]
    public struct CharacterProfile
    {
        public int level;

        public ulong exp;

        public int CreateCrdCode()
        {
            var crc = 2147483647;
            crc ^= level.GetHashCode();
            crc ^= exp.GetHashCode();
            return crc;
        }
    }
}