// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public struct CharacterDeck
	{
		public EquipmentKey[] equipmentKeys;

		public SkillKey[] skillKeys;

		public int CreateCrdCode()
		{
			var crc = 2147483647;
			crc ^= equipmentKeys.GetHashCode();
			crc ^= skillKeys.GetHashCode();
			return crc;
		}
	}
}
