// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!
namespace Glider.Core.SerializableData
{
    /// <summary>
    /// 게임 서비스 상태
    /// </summary>
	public enum GameStatusKey
	{
		InService = 0,
		UpdateRequired = 1,
		UnderMaintenance = 2,
		Undefined = -1
	}
}
