// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!
namespace Glider.Core.SerializableData
{
	public enum NavButtonKey
	{
		None = 0,
		Shop = 1,
		DisplaySide = 2,
		DisplaySideMailbox = 3,
		Research = 4,
		Close = 5,
		Accept = 6,
		AcceptAll = 7,
		Undefined = -1
	}
}
