// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!
namespace Glider.Core.SerializableData
{
	public enum NavPanelKey
	{
		Root = 0,
		Hud = 1,
		Display = 2,
		DisplaySide = 3,
		Research = 4,
		Shop = 5,
		Login = 6,
		CharacterSelect = 7,
		Mail = 8,
		Quest = 9,
		ShopFlexible = 10,
		Undefined = -1
	}
}
