// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public struct CharacterWorld
	{
		public int level;

		public int CreateCrdCode()
		{
			var crc = 2147483647;
			crc ^= level.GetHashCode();
			return crc;
		}
	}
}
