// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public struct CharacterTest
	{
		public bool isFullFace;

		[SerializeField] private int[] partIds;
		public int[] GetPartIds()
		{
			if(this.partIds == null) return null;
			var dest = new int[partIds.Length];
			Array.Copy(partIds, dest, partIds.Length);
			return dest;
		}
		public void SetPartIds(int[] value)
		{
			this.partIds = value;
		}

		public string stringTest;

		public int CreateCrdCode()
		{
			var crc = 2147483647;
			crc ^= isFullFace.GetHashCode();
			for (int i = 0; i < partIds?.Length; i++) crc ^= i.GetHashCode() ^ partIds[i].GetHashCode();
			if(stringTest!=null) crc ^= stringTest.GetHashCode();
			return crc;
		}
	}
}
