// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public struct CharacterTest
	{
		public bool isFullFace;

		public int[] partIds;

		public string stringTest;

		public int CreateCrdCode()
		{
			var crc = 2147483647;
			crc ^= isFullFace.GetHashCode();
			crc ^= partIds.GetHashCode();
			if(stringTest!=null) crc ^= stringTest.GetHashCode();
			return crc;
		}
	}
}
