// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public class SharedStaticDataWrapper : StaticDataBase
	{
        [SerializeField] private StaticDataCurrency[] currencies;
        public StaticDataCurrency[] Currencies => currencies;

        [SerializeField] private StaticDataAcquirableAsset[] acquirableAssets;
        public StaticDataAcquirableAsset[] AcquirableAssets => acquirableAssets;

        [SerializeField] private StaticDataGameStatus gameStatus;
        public StaticDataGameStatus GameStatus => gameStatus;
        public void ReloadGameStatus(StaticDataGameStatus gameStatus)=>this.gameStatus = gameStatus;

        [SerializeField] private StaticDataInAppProduct[] inAppProducts;
        public StaticDataInAppProduct[] InAppProducts => inAppProducts;

        [SerializeField] private StaticDataInAppProductContent[] inAppProductContents;
        public StaticDataInAppProductContent[] InAppProductContents => inAppProductContents;

        [SerializeField] private StaticDataSetting setting;
        public StaticDataSetting Setting => setting;

        [SerializeField] private StaticDataDeck deck;
        public StaticDataDeck Deck => deck;

        [SerializeField] private StaticDataMonster[] monsters;
        public StaticDataMonster[] Monsters => monsters;

        [SerializeField] private rateClass randomBox;
        public rateClass RandomBox => randomBox;

        [SerializeField] private StaticDataWorldLevel[] worldLevel;
        public StaticDataWorldLevel[] WorldLevel => worldLevel;

        [SerializeField] private StaticDataUnitId[] unitId;
        public StaticDataUnitId[] UnitId => unitId;

        [SerializeField] private StaticDataQuest[] quests;
        public StaticDataQuest[] Quests => quests;

        [SerializeField] private StaticDataQuestType[] questType;
        public StaticDataQuestType[] QuestType => questType;

        [SerializeField] private StaticDataReseach[] research;
        public StaticDataReseach[] Research => research;

        [SerializeField] private StaticDataNavEdge[] navEdge;
        public StaticDataNavEdge[] NavEdge => navEdge;

        [SerializeField] private StaticDataNavVertex[] navVertex;
        public StaticDataNavVertex[] NavVertex => navVertex;

	}
}
