// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public class StaticDataNav
	{
        [SerializeField] private NavButtonKey[] buttons;
        public NavButtonKey[] Buttons => buttons;

        /// <summary>
        /// 끌 수 있는지.. 예) 기본탭, 상단바
        /// </summary>
        [SerializeField] private bool isClosable;
        public bool IsClosable => isClosable;

        [SerializeField] private string name;
        public string Name => name;

        [SerializeField] private NavPanelKey panelKey;
        public NavPanelKey PanelKey => panelKey;

        /// <summary>
        /// None: -1
        /// </summary>
        [SerializeField] private int tabId;
        public int TabId => tabId;

        [SerializeField] private int uuid;
        public int Uuid => uuid;

	}
}
