// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
    /// <summary>
    /// 게임 설정에 사용되는 데이터
    /// </summary>
	[Serializable]
	public class StaticDataSetting
	{
        [SerializeField] private bool enableAppleLogin;
        public bool EnableAppleLogin => enableAppleLogin;

        [SerializeField] private bool enableGoogleLogin;
        public bool EnableGoogleLogin => enableGoogleLogin;

        [SerializeField] private string urlPrivacyPolicy;
        public string UrlPrivacyPolicy => urlPrivacyPolicy;

        [SerializeField] private string urlTerms;
        public string UrlTerms => urlTerms;

	}
}
