// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public class StaticDataWorldLevel
	{
        /// <summary>
        /// 처치 목표 몬스터 수
        /// </summary>
        [SerializeField] private int goal;
        public int Goal => goal;

        /// <summary>
        /// 월드 레벨
        /// </summary>
        [SerializeField] private int level;
        public int Level => level;

	}
}
