// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
    /// <summary>
    /// 게임 상태 체크(점검 중, 업데이트 필요 등)
    /// </summary>
	[Serializable]
	public class StaticDataGameStatus
	{
        [SerializeField] private LocalizedMessageKey lmkMaintenanceDesc;
        public LocalizedMessageKey LmkMaintenanceDesc => lmkMaintenanceDesc;

        [SerializeField] private LocalizedMessageKey lmkMaintenanceTitle;
        public LocalizedMessageKey LmkMaintenanceTitle => lmkMaintenanceTitle;

        [SerializeField] private LocalizedMessageKey lmkNoticeDesc;
        public LocalizedMessageKey LmkNoticeDesc => lmkNoticeDesc;

        [SerializeField] private LocalizedMessageKey lmkNoticeTitle;
        public LocalizedMessageKey LmkNoticeTitle => lmkNoticeTitle;

        [SerializeField] private LocalizedMessageKey lmkUpdateGuide;
        public LocalizedMessageKey LmkUpdateGuide => lmkUpdateGuide;

        [SerializeField] private string maintenanceEndTime;
        public string MaintenanceEndTime => maintenanceEndTime;

        [SerializeField] private bool showNotice;
        public bool ShowNotice => showNotice;

        [SerializeField] private GameStatusKey statusKey;
        public GameStatusKey StatusKey => statusKey;

        [SerializeField] private string urlAppStore;
        public string UrlAppStore => urlAppStore;

        [SerializeField] private string urlPlayStore;
        public string UrlPlayStore => urlPlayStore;

	}
}
