// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public class StaticDataMonster
	{
        [SerializeField] private double dropCoin;
        public double DropCoin => dropCoin;

        [SerializeField] private int id;
        public int Id => id;

        [SerializeField] private LocalizedMessageKey lmkName;
        public LocalizedMessageKey LmkName => lmkName;

        [SerializeField] private double maxHp;
        public double MaxHp => maxHp;

	}
}
