// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
	[Serializable]
	public class StaticDataUnitId
	{
        [SerializeField] private float attackRange;
        public float AttackRange => attackRange;

        [SerializeField] private int id;
        public int Id => id;

        [SerializeField] private LocalizedMessageKey lmk;
        public LocalizedMessageKey Lmk => lmk;

	}
}
