// This file was automatically generated by Gameduo Center Manager.
// Do not modify it manually!

using System;
using UnityEngine;

namespace Glider.Core.SerializableData
{
    /// <summary>
    /// 유저가 획득 가능한 모든 에셋을 미리 정의
    /// </summary>
	[Serializable]
	public class StaticDataAcquirableAsset
	{
        [SerializeField] private AcquirableAssetType acquirableAssetKey;
        public AcquirableAssetType AcquirableAssetKey => acquirableAssetKey;

        [SerializeField] private int id;
        public int Id => id;

        [SerializeField] private int keyIndex;
        public int KeyIndex => keyIndex;

        [SerializeField] private int[] param;
        public int[] Param => param;

        [SerializeField] private double value;
        public double Value => value;

	}
}
